version: '3.7'

services:
  mvpuser_db:
    image: mysql:5.7
    restart: always
    volumes:
      - mvpuser-mysql-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE:mvpuser
      - MYSQL_USER:user
      - MYSQL_PASSWORD:password
      - MYSQL_ROOT_PASSWORD:rxpad
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'

  user_svc_sys:
    links:
      - mvpuser_db
    build: ./user-service-system
    environment:
      - RUN_ENV=sit
    command: uvicorn USER_SERVICE_SYSTEM.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./user-service-system/:/dist/
    ports:
      - 8000:8000
    depends_on:
      - mvpuser_db

  demo:
    build: ./demo
    command: java -jar demo.jar
    ports:
      - 8080:8080

  producer:
    build: ./producer
    environment:
      - RUN_ENV=sit
    command: uvicorn PRODUCER.main:app --host 0.0.0.0 --port 8002
    volumes:
      - ./producer/:/dist/
    ports:
      - 8002:8002
    depends_on:
      - demo

  user_svc_prc:
    build: ./user-service-process
    environment:
      - RUN_ENV=sit
    command: uvicorn USER_SERVICE_PROCESS.main:app --host 0.0.0.0 --port 8001
    volumes:
      - ./user-service-process/:/dist/
    ports:
      - 8001:8001
    depends_on:
      - user_svc_sys
      - producer

  user_svc:
    build: ./user-service
    environment:
      - RUN_ENV=sit
    command: uvicorn USER_SERVICE.main:app --host 0.0.0.0 --port 8008
    volumes:
      - ./user-service/:/dist/
    expose:
      - 8008
    deploy:
      replicas : 2
    depends_on:
      - user_svc_prc

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx-docker/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user_svc
    ports:
      - "8003:8003"

  reverse-proxy:
    image: nginx:latest
    volumes:
      - ./reverse-proxy/proxy.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8009:8009"
    depends_on:
      - user_svc

volumes:
  mvpuser-mysql-data:
