version: '3.7'

services:
  user_svc_sys:
    build: ./user-service-system
    command: uvicorn USER_SERVICE_SYSTEM.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./user-service-system/:/dist/
    ports:
      - 8001:8000
    depends_on:
      - mvpuser_db

  mysql:
    image: mysql:5.7
    volumes:
      - mvpuser-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rxpad
      MYSQL_DATABASE: mvpuser

volumes:
  mvpuser-mysql-data: