version: '3.7'

services:
  mvpuser_db:
    image: mysql:5.7
    restart: always
    volumes:
      - mvpuser-mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: mvpuser
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rxpad
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'

  user_svc_sys:
    links:
      - mvpuser_db
    build: ./user-service-system
    command: uvicorn USER_SERVICE_SYSTEM.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./user-service-system/:/dist/
    ports:
      - 8000:8000
    depends_on:
      - mvpuser_db

volumes:
  mvpuser-mysql-data:
