version: '3.7'

services:
  user_svc_sys:
    build: ./user-service-system
    command: uvicorn USER_SERVICE_SYSTEM.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./user-service-system/:/dist/
    ports:
      - 8001:8000
    depends_on:
      - mvpuser_db
    networks:
      - local-net

  mvpuser_db:
    image: mysql:5.7
    volumes:
      - mvpuser-mysql-data:/var/lib/mysql
    environment:
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'rxpad'
      MYSQL_DATABASE: 'mvpuser'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    networks:
      - local-net

volumes:
  mvpuser-mysql-data:

networks:
  local-net:
    driver: bridge